//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import UIKit

extension AppResolver {

    func resolveDateRepositoryProtocol() -> DateRepositoryProtocol {
        return provideDateRepository()
    }

    func resolvePresenter(clock: Clock) -> Presenter {
        let useCase = resolveUseCase(clock: clock)
        return Presenter(dependency: .init(useCase: useCase))
    }

    func resolveUseCase(clock: Clock) -> UseCase {
        let dateRepositoryProtocol = resolveDateRepositoryProtocol()
        return UseCase(dependency: .init(dateRepository: dateRepositoryProtocol, clock: clock))
    }

    func resolveViewController(clock: Clock) -> ViewController {
        let presenter = resolvePresenter(clock: clock)
        return ViewController.makeInstance(dependency: .init(presenter: presenter))
    }

}

